;Bubble Sort
org 100h;
ARRAY DB 11H, 99H, 22H, 88H, 33H, 77H, 44H, 55H
COUNT DW 8

MOV CX, COUNT ; CX=8
DEC CX
NEXTSCAN: MOV BX,CX ; BX STORES THE NUMBER OF COMPARISONS
          MOV SI, 0
NEXTCOMP: MOV AL, ARRAY[SI]
          MOV DL, ARRAY[SI+1]
          CMP AL, DL ; AL-DL
          JC NOSWAP ; MAIN CONDITION FOR CHECKING TWO NUMBERS
          MOV ARRAY[SI], DL
          MOV ARRAY[SI+1], AL
NOSWAP: INC SI
        DEC BX
        JNZ NEXTCOMP
        LOOP NEXTSCAN ; CX IS AYTOMATICALLY DECREMENTED IN LOOP
