; Automatically fills the first block by the given number of values and
; then puts it into the second block in reverse order

org 100h
; allocate space for the blocks
NUM DW 5; NUMBER OF ELEMENTS TO BE USED
BLOCK1 DW 15 DUP(?); ALLOCATE A SUFFICIENTLY LARGE MEMORY AREA FOR BOTH BLOCKS
BLOCK2 DW 15 DUP(?)

CLD; CLEAR DIRECTION FLAG (AUTO-INCREMENT)

MOV BX, 0 ; USED TO GENERATE INCREMENTAL NUMBERS 1,2,3,..
MOV CX, NUM
MOV DI, 0
; FILL THE FIRST BLOCK
L0: INC BX
    MOV BLOCK1[DI], BX ; FILL THE WORD POSITIONS IN THE FIRST BLOCK
    ADD DI, 2 ; NEXT WORD POSITION
    DEC CX
    CMP CX,  0 ; COMPARE CX AGAINST 0
    JNZ L0; THIS WILL STOP JUMPING WHEN CX BECOMES 0

; NOW REVERSE THE BLOCK
MOV CX, NUM

MOV SI, OFFSET BLOCK1
MOV DI, OFFSET BLOCK2

; PUSH TO STACK
L1: LODSW
    PUSH AX
    LOOP L1

MOV CX, NUM
;POP FROM STACK
L2: POP AX
    STOSW
    LOOP L2

HLT
