; FIND THE LARGEST ELEMENT IN AN ARRAY AND STORE IT IN DX.
; THE ARRAY ENDS WITH AN 0XAA END-OF-BLOCK VALUE


ORG 100H

ARRAY DB 11H, 22H, 88H, 99H, 33H, 77H, 44H, 55H, 0XAA

CLD; AUTO-INCREMENT 

MOV SI, OFFSET ARRAY 
BOX BX, 0; COMPARE ALL WITH BX AND STORE THE TEMP RESULT THEREIN.

L0:
	LODS
	CMP AX,0XAA 
	JZ END 
	CMP AX, BX 
	JB CONTINUE:
	MOV BX, AX

CONTINUE:
	JMP L0 
	
END:
	MOV DX, BX 
	HLT